

class CalcMatrix:
	def __init__(self, data, states_list_not_final, states_list_final,  names_sem: list):
		# note that the number of directions is autogenerated
		self.num_dir = 3
		self.number_states = len(states_list_not_final)
		self.states_list = states_list_not_final
		self.states_list_len = len(states_list_not_final)
		self.states_list_final = states_list_final
		self.states_list_final_len = len(states_list_final)
		self.data = data
		self.names_sem = names_sem

	def create_matrix(self, action: str):
		my_action = [action]
		my_matrix = []
		# we go through each state ( iteration of rows in matrix )
		row = 0
		# while row < self.number_states:
		column1 = 0
		first_row = ["Initial state"]
		while column1 < self.states_list_len:
			first_row.append(self.states_list_final[column1])
			column1 += 1
		my_matrix.append(first_row)
		while row < self.states_list_len:
			new_row = [self.states_list[row]]
			column = 0
			# my_counter = 0
			# my_counter_all = 0
			# we go through each state ( iteration in columns for each row )
			# while column < self.number_states - 1:
			while column < self.states_list_final_len:
				i = 1
				my_counter = 0
				my_counter_all = 0
				while i < len(self.data):
					if self.data[i][0] == self.states_list[row] and self.data[i][1] == my_action:
						my_counter_all += 1
						if self.data[i][2] == self.states_list_final[column]:
							my_counter += 1
					i += 1
				column += 1

				new_row.append(my_counter / my_counter_all)
			my_matrix.append(new_row)
			row += 1

		return my_matrix























